apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-iu8c
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/quay-or-not-to-quay/nbe-e2e-xubl-tenant/integ-app-jyhy/hacbs-test-project-iu8c@sha256:559c98f51a4355ea5e978136d547b2f6b4861edd8b083846c80f0799bfa1f1d8
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
